services:
    ${organization_name}-gateway-app:
        image: "${gateway_image}"
        external_links:
            - gateway-mysql-${organization_name}:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@192.168.99.101:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://gateway-mysql-${organization_name}:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - ORGANIZATION_NAME=${organization_name}
        ports:
            - ${organization-port}:80

    gateway-mysql-${organization_name}:
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gateway
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
