services:
    gateway-app:
        image: "${gateway_image}"
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@192.168.99.101:8761/config
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - ORGANIZATION_NAME=${organization_name}
        ports:
            - "${organization_port}:80"
    gateway-mysql:
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gateway
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
