version: '2'
services:
    gateway-app:
        image: "${gateway_image}"
        external_links:
            - gateway-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@104.198.133.169:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://gateway-mysql:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - ORGANIZATION_NAME=${organization_name}
        ports:
            - "${organization_port}:80"

    gateway-mysql:
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gateway
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
    mysql:
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ccs
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8

    groundstation-app:
        image: "${gs_image}"
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@104.198.133.169:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ccs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - ORGANIZATION_NAME=${organization_name}

    spacecraft-app:
        image: "${sc_image}"
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@104.198.133.169:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ccs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - ORGANIZATION_NAME=${organization_name}
    
    telecommand-app:
        image: "${tc_image}"
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@104.198.133.169:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ccs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - ORGANIZATION_NAME=${organization_name}


  
